### ISSUE TITLE
`int` not found in this scope

### ISSUE THREAD

**Issue by KarateCowboy** [pest-parser/book#2]
Hi

First, thank you for your hard work and ambition in creating Pest, and in documenting it.

I would like to use your library in my Ruby interpreter. I am trying to follow your examples. For some reason, I receive the error:

```
cargo test
   Compiling sunrise v0.1.0 (file:///home/moriger/Projects/sunrise)
warning: unused `#[macro_use]` import
 --> src/lib.rs:1:1
  |
1 | #[macro_use]
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error[E0425]: cannot find function `int` in this scope
  --> src/lib.rs:67:36
   |
67 |             tokens: [ float(0, 2 [ int(0,1) ]) ]
   |                                    ^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
16 |     use Rule::int;
   |
```
I am very much at a loss as what to do. I am new to Rust and new to Pest and dumbfounded. Here is a link to my code, in case maybe I am missing something:

 

https://github.com/KarateCowboy/Sunrise/blob/convert-to-pest/src/lib.rs#L63

**Comment by dragostis** [comment]
You're missing a comma before the `[`. (`float(0, 2, [int(0, 1)])`)

**Comment by KarateCowboy** [comment]
Thank you.

I feel pretty embarrassed now.

**Comment by dragostis** [comment]
> I feel pretty embarrassed now.

Happens to me every time.
