### ISSUE TITLE
Calculator example

### ISSUE THREAD

**Issue by wildarch** [pest-parser/book#22]
I noticed the calculator example part of the book is not yet written. I used pest in a recent project a struggled a bit to figure out how to use the precedence climber.

I am putting together a [small tutorial](https://github.com/wildarch/pest-calculator/blob/main/docs/Tutorial.md) on how to build a calculator in pest, would the maintainers of this repo be interested in merging that into the book? I'm happy to submit a pull request :smile:

**Comment by tomtau** [comment]
@wildarch yes, feel free to open a PR! 🙏

**Comment by wildarch** [comment]
Sorry I didn't get to this in time @tomtau, thanks for putting in the effort :smile:

**Comment by tomtau** [comment]
No problem @wildarch ! Thank you for the initial tutorial write-up! 🙏
