### ISSUE TITLE
License

### ISSUE THREAD

**Issue by prkadalb** [pest-parser/book#33]
Hello everyone,

I want to use the json example in the book in my project and want to know what is the license applicable for this?

As pest itself is dual licensed under MIT/Apache 2.0, I assume the book examples would also be so, but I came across a crate in crates.io which was publishing the same examples under AGPL.

It would be very helpful if a license was added to this repo.

Thank you!

**Comment by LeoDog896** [comment]
@tomtau similar to https://github.com/pest-parser/site/issues/16 - the earlier this is done the better

**Comment by tomtau** [comment]
ok, I take it that @dragostis 's reply applies here as well: https://github.com/pest-parser/site/issues/16#issuecomment-1451904838 so will add the same license as the main repo
