### ISSUE TITLE
Add example for negation operator

### ISSUE THREAD

**Issue by jstnlef** [pest-parser/book#8]
From @indeyets:

`!a` doesn't have any practical examples. it should have one.

It would be useful to show `!["}"] ~ any` pattern or something similar ("anything but delimiter is allowed")

**Comment by wirelyre** [comment]
Is this adequately addressed in [the predicates section](https://github.com/pest-parser/book/blob/2d50ffab542813a4db33cefdf49e548ab039ea3c/src/grammars/syntax.md#predicates)?

**Comment by jstnlef** [comment]
Addressed!
